# -*- coding: utf-8 -*-
"""Nasa hackathon 2.0 use the saved model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pUjcw8fymL6cY1Wk0BYvJE-iCOdbQY-0

# install gdown
"""

# !pip install gdown==4.6.3
# from IPython.display import clear_output

# clear_output()

"""# install dataset

https://drive.google.com/file/d/1surad1nR2zgxq9iir8sSA4mfVBKm6RcD/view?usp=sharing
"""

# !gdown 1surad1nR2zgxq9iir8sSA4mfVBKm6RcD

"""# install saved model"""

# !gdown 1_Ad5Al7ZYeriQKfYW7ZNgKe85Iavtsvy
# !gdown 1ClyIKlb-xEOPCsWAnoKSzAZ3-Pk1c8rV

"""# Predict"""

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
import joblib
from datetime import datetime

def create_model(input_shape):
    model = Sequential([
        LSTM(50, activation='relu', input_shape=input_shape),
        Dense(25, activation='relu'),
        Dense(1)
    ])
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

loaded_model = create_model((1, 5))
loaded_model.load_weights('riyadh_aot_lstm_v2.weights.h5')
loaded_scaler = joblib.load('riyadh_aot_scaler_v2.pkl')

def predict_aot_batch(input_array):
    # Prepare input data
    processed_inputs = []
    for row in input_array:
        latitude, longitude, current_aot, prediction_date = row
        day_of_year = prediction_date.timetuple().tm_yday
        month = prediction_date.month
        processed_inputs.append([latitude, longitude, current_aot, day_of_year, month])

    processed_inputs = np.array(processed_inputs)

    # Scale the inputs
    inputs_scaled = loaded_scaler.transform(processed_inputs)
    inputs_reshaped = np.reshape(inputs_scaled, (inputs_scaled.shape[0], 1, 5))

    # Make predictions
    predictions = loaded_model.predict(inputs_reshaped)

    return predictions.flatten()


if __name__ == "__main__":
    # Example input array
    input_array = np.array([
        [24.7136, 46.6753, 0.5, datetime(2024, 10, 15)],
        [24.7136, 46.6753, 0.6, datetime(2024, 10, 16)],
        [24.7136, 46.6753, 0.4, datetime(2024, 10, 17)]
    ])

    predicted_aots = predict_aot_batch(input_array)

    for i, prediction in enumerate(predicted_aots):
        print(f"Prediction {i+1}: {prediction:.4f}")